mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    #path('thoughts/', views.ThoughtsView.as_view(), name='thoughts'),
    path('thoughts/', views.thoughts, name='thoughts'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py

import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Thoughts(models.Model):
    thought_text = models.CharField(max_length=200)
    post_date = models.DateTimeField('date posted')

    def __str__(self):
        return self.thought_text

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question, Thoughts

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

#class ThoughtsView(generic.ListView):
 #   model = Thoughts
  #  template_name = 'polls/thoughts.html'
    # get all of the thoughts
   # def get_queryset(self):
    #    return Thoughts.objects.all()


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))


thoughtPosts = [
    {
        'title': 'first title',
        'thought_text': 'first text'
    },
    {
        'title': 'second title',
        'thought_text': 'second text'
    }
]




def thoughts(request):
    thoughtList = {
        'allThoughts': thoughtPosts
    }
    return render(request, 'polls/thoughts.html', thoughtList)


polls/templates/polls/detail.html
<!doctype html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <title>Question</title>
      </head>
      <header>
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand">Question</a>
                <form class="form-inline">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </nav>
      </header>
      <body>
        <h1>{{ question.question_text }}</h1>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
          {% csrf_token %}
          {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
          {% endfor %}
          <input type="submit" value="Vote">
        </form>
        <form action="{% url 'polls:thoughts'%}">
          {% csrf_token %}
          <input type="submit" value="Thoguhts on Polls?">
        </form>
      </body>
      <footer class="bg-light text-center text-lg-start">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
          Header:
          © 2021 Copyright:
          <a class="text-dark" href="https://getbootstrap.com/"> getbootstrap.com.<br /></a>
          Footer:
          © 2020 Copyright:
          <a class="text-dark" href="https://mdbootstrap.com/"> MDBootstrap.com.<br /></a>
          Overall:
          @ 2021 Copyright: William McCarty
        </div>
      </footer>
</html>

polls/templates/polls/index.html
<!doctype html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <title>Home</title>
      </head>
      <header>
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand">Home</a>
                <form class="form-inline">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </nav>
      </header>
      <body>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
        {% if latest_question_list %}
          <ul>
            {% for question in latest_question_list %}
              <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
            {% endfor %}
          </ul>
          <form action="{% url 'polls:thoughts'%}">
            {% csrf_token %}
            <input type="submit" value="Thoguhts on Polls?">
          </form>
        {% else %}
          <p>No polls are available.</p>
          <li><a href='{% url 'polls:thoughts' %}>{{'Thoughts on Polls? If so click here to give them.'}}</a></li>
        {% endif %}
      </body>
      <footer class="bg-light text-center text-lg-start">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
          Header:
          © 2021 Copyright:
          <a class="text-dark" href="https://getbootstrap.com/"> getbootstrap.com.<br /></a>
          Footer:
          © 2020 Copyright:
          <a class="text-dark" href="https://mdbootstrap.com/"> MDBootstrap.com.<br /></a>
          Overall:
          @ 2021 Copyright: William McCarty
        </div>
      </footer>
</html>

polls/templates/polls/results.html
<!doctype html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <title>Results</title>
      </head>
      <header>
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand">Results</a>
                <form class="form-inline">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </nav>
      </header>
      <body>
        <h1>{{ question.question_text }}</h1>
        <ul>
        {% for choice in question.choice_set.all %}
            <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
        {% endfor %}
        </ul>
        <form action="{% url 'polls:detail' question.id %}">
          {% csrf_token %}
          <input type="submit" value="Vote Again?">
        </form>
      </body>
      <footer class="bg-light text-center text-lg-start">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
          Header:
          © 2021 Copyright:
          <a class="text-dark" href="https://getbootstrap.com/"> getbootstrap.com.<br /></a>
          Footer:
          © 2020 Copyright:
          <a class="text-dark" href="https://mdbootstrap.com/"> MDBootstrap.com.<br /></a>
          Overall:
          @ 2021 Copyright: William McCarty
        </div>
      </footer>
</html>

polls/templates/polls/thoughts.html
<!doctype html>
<html lang="en">
      <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <title>Thoughts</title>
      </head>
      <header>
            <nav class="navbar navbar-light bg-light">
                <a class="navbar-brand">Thoughts</a>
                <form class="form-inline">
                  <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </nav>
      </header>
      <body>
            {% if allThoughts %}
              {% for tho in allThoughts %}
                <h2>{{tho.title}}</h2>
                <p>{{tho.thought_text}}</p>
              {% endfor %}
            {% else %}
              <h1>"fail"</h1>
            {% endif %}
            <form action="{% url 'polls:thoughts'%}">
              <lable for="ntitle">Title:</label>
              <input type="text" id ="ntitle" name="ntitle"><br><br>
              <label for="ntext">Text:</label>
              <input type="text" id ="ntext" name="ntext"><br><br>
              <input type="submit" value="Submit Thought"><br><br>
            </form>
            <form action="{% url 'polls:index'%}">
              {% csrf_token %}
              <input type="submit" value="Return Home?">
            </form>
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
      </body>
      <footer class="bg-light text-center text-lg-start">
        <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
          Header:
          © 2021 Copyright:
          <a class="text-dark" href="https://getbootstrap.com/"> getbootstrap.com.<br /></a>
          Footer:
          © 2020 Copyright:
          <a class="text-dark" href="https://mdbootstrap.com/"> MDBootstrap.com.<br /></a>
          Overall:
          @ 2021 Copyright: William McCarty
        </div>
      </footer>
</html>